name: Sync with upstream
on:
  schedule:
    - cron: "28 */4 * * *"
  workflow_dispatch:

jobs:
  sync-mirror:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Update mirror
        uses: projg2/crate-dist-mirror-action@v2
        with:
          ssh-private-key: ${{ secrets.ssh_key }}
