name: Sync with upstream
on:
  schedule:
    - cron: "8 * * * *"

jobs:
  sync-mirror:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Update mirror
        uses: projg2/crate-dist-mirror-action@v1
        with:
          ssh-private-key: ${{ secrets.ssh_key }}
